/**
 * Collected-item categories for the ewi schema.
 * Keep this list aligned with EwiEvidenceCategory in schema.prisma.
 * Inconsistencies, cross-examination questions, and the Word report
 * stay on their existing tables.
 */
export const EWI_EVIDENCE_CATEGORIES = [
  'identity_profile',
  'location',
  'specialty',
  'cv',
  'education',
  'university',
  'license',
  'state_license',
  'board_certification',
  'certification_organization',
  'membership',
  'publication',
  'grant',
  'patent',
  'award',
  'military',
  'legal_case',
  'court_order',
  'motion',
  'deposition',
  'testimony',
  'directory',
  'website',
  'ime',
  'advertising',
  'video',
  'presentation',
  'powerpoint',
  'social',
  'news',
  'university_rules',
  'income_bias',
  'patient_review',
  'office',
  'corporate_affiliation',
  'criminal_record',
  'malpractice',
  'foia_request',
  'university_request',
  'graduation_request',
  'research_finding',
] as const;

export type EwiEvidenceCategory = (typeof EWI_EVIDENCE_CATEGORIES)[number];

const CATEGORY_ALIASES: Record<string, EwiEvidenceCategory> = {
  profile: 'identity_profile',
  identity: 'identity_profile',
  identity_profile: 'identity_profile',
  location: 'location',
  city: 'location',
  specialty: 'specialty',
  cv: 'cv',
  curriculum_vitae: 'cv',
  education: 'education',
  degree: 'education',
  university: 'university',
  accreditation: 'university',
  license: 'license',
  state_license: 'state_license',
  board: 'board_certification',
  board_certification: 'board_certification',
  certification_organization: 'certification_organization',
  membership: 'membership',
  publication: 'publication',
  grant: 'grant',
  patent: 'patent',
  trademark: 'patent',
  award: 'award',
  medal: 'award',
  military: 'military',
  legal: 'legal_case',
  legal_case: 'legal_case',
  case: 'legal_case',
  order: 'court_order',
  court_order: 'court_order',
  motion: 'motion',
  pleading: 'motion',
  deposition: 'deposition',
  testimony: 'testimony',
  directory: 'directory',
  website: 'website',
  ime: 'ime',
  advertising: 'advertising',
  video: 'video',
  presentation: 'presentation',
  powerpoint: 'powerpoint',
  social: 'social',
  news: 'news',
  blog: 'news',
  university_rules: 'university_rules',
  income_bias: 'income_bias',
  patient_review: 'patient_review',
  office: 'office',
  address: 'office',
  corporate_affiliation: 'corporate_affiliation',
  criminal_record: 'criminal_record',
  criminal: 'criminal_record',
  malpractice: 'malpractice',
  foia_request: 'foia_request',
  foia: 'foia_request',
  university_request: 'university_request',
  graduation_request: 'graduation_request',
  graduation: 'graduation_request',
  research_finding: 'research_finding',
};

export function mapEvidenceCategory(sourceType: string): EwiEvidenceCategory {
  const key = sourceType
    .trim()
    .toLowerCase()
    .replace(/[\s-]+/g, '_');
  return CATEGORY_ALIASES[key] ?? 'research_finding';
}
