export const EWI_PROGRESS_STEPS = [
  { id: "identify-expert", label: "Identify Expert" },
  {
    id: "profiles",
    label: "Confirm identity (NPI) and find professional profiles",
  },
  { id: "education", label: "Verify education and degrees" },
  { id: "licenses", label: "Verify medical licenses" },
  { id: "boards", label: "Verify board certifications" },
  { id: "publications", label: "Research publications and authorship" },
  { id: "grants", label: "Research grants" },
  { id: "patents", label: "Research patents" },
  { id: "awards", label: "Research awards and medals" },
  {
    id: "memberships",
    label: "Research memberships and professional organizations",
  },
  {
    id: "legal",
    label: "Research legal cases, motions, orders and available references",
  },
  { id: "directories", label: "Research expert witness directories" },
  { id: "websites", label: "Research expert websites and advertising" },
  { id: "ime", label: "Research IME-related information" },
  { id: "videos", label: "Research YouTube/videos/presentations" },
  { id: "social", label: "Research public social media" },
  { id: "news", label: "Research news and blogs" },
  { id: "university-rules", label: "Research university/professional rules" },
  {
    id: "public-records",
    label:
      "Research reviews, payments, criminal background, and public affiliations",
  },
  { id: "cross-check", label: "Cross-check information" },
  { id: "discrepancies", label: "Identify inconsistencies" },
  { id: "analyze-legal", label: "Analyze legal materials" },
  { id: "analyze-presence", label: "Analyze online presence" },
  { id: "analyze-financial", label: "Analyze income and bias information" },
  { id: "summary", label: "Generate investigation summary" },
  { id: "questions", label: "Generate cross-examination questions" },
  { id: "report", label: "Generate final report" },
] as const;

/** Suggestions only. The field still accepts any other specialty the user types. */
export const EWI_SPECIALTY_EXAMPLES = [
  "Allergy",
  "Anesthesiology",
  "Cardiology",
  "Dermatology",
  "Emergency Medicine",
  "Family Practice",
  "General Practice",
  "General Surgery",
  "Internal Medicine",
  "Neurology",
  "Neuroradiology",
  "Neuropsychology",
  "Neurosurgery",
  "Obstetrics",
  "Occupational Medicine",
  "Ophthalmology",
  "Orthopedic Surgery",
  "Otolaryngology",
  "Pain Management",
  "Pathology",
  "Pediatrics",
  "Plastic Surgery",
  "Psychiatry",
  "Psychology",
  "Pulmonology",
  "Radiology",
  "Thoracic Surgery",
  "Toxicology",
  "Vascular Surgery",
] as const;
