export const EWI_PROGRESS_STEPS = [
  { id: "identify-expert", label: "Identify Expert" },
  { id: "profiles", label: "Find CV and professional profiles" },
  { id: "education", label: "Verify education and degrees" },
  { id: "licenses", label: "Verify medical licenses" },
  { id: "boards", label: "Verify board certifications" },
  { id: "publications", label: "Research publications and authorship" },
  { id: "grants", label: "Research grants" },
  { id: "patents", label: "Research patents" },
  { id: "awards", label: "Research awards and medals" },
  {
    id: "legal",
    label: "Research legal cases, motions, orders and available references",
  },
  { id: "directories", label: "Research expert witness directories" },
  { id: "websites", label: "Research expert websites and advertising" },
  { id: "ime", label: "Research IME-related information" },
  { id: "videos", label: "Research YouTube/videos/presentations" },
  { id: "social", label: "Research public social media" },
  { id: "news", label: "Research news and blogs" },
  { id: "university-rules", label: "Research university/professional rules" },
  { id: "cross-check", label: "Cross-check information" },
  { id: "discrepancies", label: "Identify discrepancies" },
  { id: "summary", label: "Generate investigation summary" },
  { id: "questions", label: "Generate cross-examination questions" },
  { id: "report", label: "Generate final report" },
] as const;

export const EWI_SPECIALTY_EXAMPLES = [
  "Neurology",
  "Orthopedic Surgery",
  "Psychiatry",
  "Radiology",
  "Pain Management",
] as const;
