import {
  REPORT_POLICY_FOOTER,
  REPORT_POLICY_SECTIONS,
} from "@/features/report/report-terms";

export function ReportTermsSection() {
  return (
    <section
      id="report-terms-policy"
      className="report-export-block report-terms break-before-page rounded-xl border border-border/80 bg-muted/20 p-6 sm:p-8"
    >
      <p className="text-xs font-semibold uppercase tracking-[0.2em] text-primary">
        Terms, Conditions &amp; Policy
      </p>
      <h2 className="mt-2 text-xl font-semibold text-foreground">
        Important Legal Notice
      </h2>
      <p className="mt-3 text-sm leading-7 text-muted-foreground">
        This report is generated by Medical Causation AI. Please review the
        following terms before relying on this output in any legal, medical, or
        business context.
      </p>

      <div className="mt-6 space-y-5">
        {REPORT_POLICY_SECTIONS.map((section) => (
          <div key={section.title}>
            <h3 className="text-sm font-semibold text-foreground">
              {section.title}
            </h3>
            <p className="mt-2 text-sm leading-7 text-muted-foreground">
              {section.body}
            </p>
          </div>
        ))}
      </div>

      <p className="mt-6 border-t border-border/70 pt-4 text-xs leading-6 text-muted-foreground">
        {REPORT_POLICY_FOOTER}
      </p>
    </section>
  );
}
