import type {
  CrossExamCategory,
  MedicalAnalysisRequest,
  PublicReference,
  RiskFactor,
  TimelineEvent,
} from '../types';

export const LEGAL_DISCLAIMER_TEXT = `This report is generated by Medical Causation AI for informational and legal research purposes only. It does not constitute medical advice, diagnosis, or treatment. It is not a substitute for evaluation by a licensed healthcare professional. No warranty is made as to accuracy, completeness, or currency of the research. Users assume all risk in relying on this output. See Terms of Use for full limitations of liability, arbitration, and governing law (California).`;

const PUBLIC_SOURCE_POOL: Array<{
  keywords: RegExp;
  refs: Omit<PublicReference, 'id'>[];
}> = [
  {
    keywords: /stroke|ischemic|cerebrovascular|tbi|brain injury|concussion/i,
    refs: [
      {
        title: 'Traumatic brain injury and risk of subsequent neurological sequelae',
        source: 'PubMed',
        url: 'https://pubmed.ncbi.nlm.nih.gov/',
        year: 2022,
        excerpt: 'Epidemiological associations between mild TBI and delayed cerebrovascular events.',
      },
      {
        title: 'NIH Stroke Scale and delayed stroke after head trauma',
        source: 'NIH',
        url: 'https://www.nih.gov/',
        year: 2021,
        excerpt: 'Clinical guidance on monitoring neurological deterioration after traumatic injury.',
      },
      {
        title: 'Inflammatory pathways linking TBI to cerebrovascular disease',
        source: 'PubMed Central',
        url: 'https://www.ncbi.nlm.nih.gov/pmc/',
        year: 2023,
        excerpt: 'Biological plausibility for delayed ischemic events post-concussion.',
      },
      {
        title: 'Post-TBI cerebrovascular outcomes registry',
        source: 'ClinicalTrials.gov',
        url: 'https://clinicaltrials.gov/',
        year: 2024,
        excerpt: 'Prospective studies of vascular outcomes after mild TBI.',
      },
      {
        title: 'mTBI and stroke risk meta-analysis',
        source: 'Semantic Scholar',
        url: 'https://www.semanticscholar.org/',
        year: 2020,
        excerpt: 'Pooled effect estimates for stroke following traumatic brain injury.',
      },
      {
        title: 'WHO traumatic brain injury fact sheet',
        source: 'WHO',
        url: 'https://www.who.int/',
        year: 2023,
        excerpt: 'Global epidemiology and long-term sequelae of TBI.',
      },
      {
        title: 'CDC HEADS UP concussion management guidelines',
        source: 'CDC',
        url: 'https://www.cdc.gov/',
        year: 2022,
        excerpt: 'Public health guidance on concussion recognition and follow-up.',
      },
    ],
  },
  {
    keywords: /cervical|radiculopathy|disc|whiplash|neck/i,
    refs: [
      {
        title: 'Cervical disc herniation after motor vehicle collision',
        source: 'PubMed',
        url: 'https://pubmed.ncbi.nlm.nih.gov/',
        year: 2021,
        excerpt: 'Incidence and causation of acute cervical disc injury after whiplash.',
      },
      {
        title: 'AMA Guides cervical spine impairment evaluation',
        source: 'Crossref',
        url: 'https://www.crossref.org/',
        year: 2022,
        excerpt: 'Standardized methodology for cervical spine causation analysis.',
      },
      {
        title: 'NIH cervical radiculopathy clinical overview',
        source: 'NIH',
        url: 'https://www.nih.gov/',
        year: 2020,
        excerpt: 'Degenerative vs traumatic etiology of nerve root compression.',
      },
      {
        title: 'Whiplash-associated disorders systematic review',
        source: 'PubMed Central',
        url: 'https://www.ncbi.nlm.nih.gov/pmc/',
        year: 2019,
        excerpt: 'Temporal onset of cervical symptoms after MVC.',
      },
    ],
  },
  {
    keywords: /lumbar|disc herniation|back|workplace|fall/i,
    refs: [
      {
        title: 'Occupational low back injury and disc herniation',
        source: 'PubMed',
        url: 'https://pubmed.ncbi.nlm.nih.gov/',
        year: 2022,
        excerpt: 'Work-related fall mechanisms and acute lumbar disc extrusion.',
      },
      {
        title: 'CDC workplace fall injury epidemiology',
        source: 'CDC',
        url: 'https://www.cdc.gov/',
        year: 2023,
        excerpt: 'Biomechanics of fall-related back trauma.',
      },
      {
        title: 'Degenerative vs traumatic lumbar disc pathology',
        source: 'Semantic Scholar',
        url: 'https://www.semanticscholar.org/',
        year: 2021,
        excerpt: 'Distinguishing acute traumatic disc injury from degeneration.',
      },
    ],
  },
];

const DEFAULT_PUBLIC_REFS: Omit<PublicReference, 'id'>[] = [
  {
    title: 'Medical causation analysis in personal injury litigation',
    source: 'PubMed',
    url: 'https://pubmed.ncbi.nlm.nih.gov/',
    year: 2021,
    excerpt: 'Framework for evaluating trauma-disease causation in legal contexts.',
  },
  {
    title: 'NIH evidence-based medicine and causation standards',
    source: 'NIH',
    url: 'https://www.nih.gov/',
    year: 2022,
    excerpt: 'Federal guidance on evaluating medical evidence strength.',
  },
];

export function simulatePublicReferences(
  medicalQuestion: string,
  diagnosis?: string,
): PublicReference[] {
  const text = `${medicalQuestion} ${diagnosis ?? ''}`;
  const matched = PUBLIC_SOURCE_POOL.find((pool) => pool.keywords.test(text));
  const pool = matched?.refs ?? DEFAULT_PUBLIC_REFS;
  return pool.map((ref, index) => ({ id: `pub-${index + 1}`, ...ref }));
}

export function buildTimelineEvents(
  request: MedicalAnalysisRequest,
  conclusion: string,
): TimelineEvent[] {
  const events: TimelineEvent[] = [];

  if (request.accidentDate) {
    events.push({
      date: request.accidentDate,
      event: 'Index accident / injury event',
      significance: 'Establishes temporal starting point for causation analysis.',
    });
  }

  if (request.medicalHistory?.includes('Timeline:')) {
    const timelineSection = request.medicalHistory.split('Timeline:')[1] ?? '';
    for (const line of timelineSection
      .split('\n')
      .map((l) => l.trim())
      .filter(Boolean)
      .slice(0, 8)) {
      const parts = line.split(/[—–-]/);
      events.push({
        date: parts[0]?.trim() ?? 'Undated',
        event: parts.slice(1).join('—').trim() || line,
        significance: 'Clinical milestone relevant to causation timeline.',
      });
    }
  }

  if (events.length < 2) {
    events.push({
      date: 'Follow-up',
      event: 'Subsequent diagnosis and treatment period',
      significance:
        conclusion.slice(0, 120) + (conclusion.length > 120 ? '…' : ''),
    });
  }

  return events;
}

export function inferRiskFactors(
  request: MedicalAnalysisRequest,
  opposingCount: number,
): RiskFactor[] {
  const factors: RiskFactor[] = [];
  const history = `${request.medicalHistory ?? ''} ${request.preExistingConditions ?? ''}`.toLowerCase();

  if (/hypertension|hyperlipidemia|diabetes|smok|obesity|bmi/i.test(history)) {
    factors.push({
      factor: 'Cardiovascular / metabolic comorbidities',
      category: 'comorbidity',
      impact: 'May provide alternative pathways independent of traumatic injury.',
    });
  }
  if (/degenerative|prior|previous|chronic|pre-existing/i.test(history)) {
    factors.push({
      factor: 'Pre-existing or degenerative conditions',
      category: 'pre-existing',
      impact: 'Competing etiology weighed against traumatic mechanism.',
    });
  }
  if (opposingCount > 0) {
    factors.push({
      factor: 'Opposing evidence in literature review',
      category: 'other',
      impact: `${opposingCount} source(s) present evidence against causation.`,
    });
  }
  if (factors.length === 0) {
    factors.push({
      factor: 'Limited documented risk factor data',
      category: 'other',
      impact: 'Additional records may be needed for complete differential analysis.',
    });
  }
  return factors;
}

const CROSS_EXAM_TEMPLATES: Record<string, string[]> = {
  'Medical Causation': [
    'Doctor, you agree that establishing medical causation requires more than temporal association, correct?',
    "Isn't it true that correlation between the accident and diagnosis does not prove causation?",
    "Can you identify alternative explanations for the patient's condition besides the accident?",
    'What objective criteria did you use to determine the accident caused this condition?',
    'You agree pre-existing conditions can mimic post-accident symptoms?',
    'Is there epidemiological data quantifying risk from this specific mechanism?',
    'How do you account for the natural history of this condition without trauma?',
    'Your opinion assumes the accident history is accurate and complete, correct?',
  ],
  'Prior Medical History': [
    'You reviewed prior medical records before forming your opinion, correct?',
    "The patient had documented medical issues before the accident, didn't they?",
    'Prior symptoms can reduce confidence the accident alone caused the diagnosis, correct?',
    'Failure to document pre-accident baseline limits causation certainty?',
    'Did you consider whether symptoms predated the index event?',
    'Is it possible pre-existing conditions fully explain the findings?',
    'What weight did you give comorbidities in your analysis?',
    'An incomplete history can lead to over-attribution to trauma, correct?',
  ],
  'Imaging Findings': [
    'Imaging alone cannot establish traumatic causation without clinical correlation, correct?',
    "Degenerative changes are common in this age group on imaging, aren't they?",
    'Can you point to imaging findings pathognomonic for acute trauma?',
    'Chronic MRI changes can predate the accident, correct?',
    'Were studies compared to any pre-accident baseline films?',
    'Could imaging reflect age-related rather than acute traumatic changes?',
    'What feature distinguishes traumatic from degenerative etiology?',
    'Radiological findings must be interpreted in clinical context, correct?',
  ],
  'Differential Diagnosis': [
    'What alternative diagnoses did you consider and rule out?',
    'Multiple conditions can produce identical symptoms, correct?',
    'How did you exclude non-traumatic causes?',
    'A thorough differential is essential for causation opinions, correct?',
    'Could idiopathic onset explain the diagnosis?',
    'Is there a finding that definitively excludes non-traumatic cause?',
    'What evidence supports your conclusion over competing diagnoses?',
    'Unexplained symptoms require caution in attributing causation, correct?',
  ],
  'Medical Literature': [
    'You relied on published literature in forming your opinion, correct?',
    'Not all published studies support a causal relationship here, do they?',
    'Can you cite peer-reviewed studies with effect sizes for this mechanism?',
    'Literature must be current and methodologically sound, correct?',
    'Are you aware of studies contradicting your conclusion?',
    'How do you reconcile conflicting evidence in the literature?',
    'Did you perform a systematic review or rely on selected articles?',
    'Anecdotal reports are insufficient for causation opinions, correct?',
  ],
  'Standard of Care': [
    'Your role is causation opinions, not treatment recommendations, correct?',
    'Treating physicians may disagree on causation without breaching standard of care?',
    'You are not the treating physician in this case, are you?',
    'Retrospective analysis has limitations vs contemporaneous evaluation?',
    'Did treating providers document causation opinions consistent with yours?',
    'Reasonable physicians could disagree on causation here, correct?',
    'What guidelines govern your causation methodology?',
    'Your opinion must be based on reasonable medical probability, not speculation?',
  ],
  'Expert Credibility': [
    'You are being compensated for your testimony today, correct?',
    'You have offered similar opinions in other litigation matters?',
    'How many times have you testified for plaintiffs vs defendants?',
    'Intellectual honesty requires acknowledging evidence against your position?',
    'Did you consider all records or only those supporting your opinion?',
    'Is any portion of your opinion based on assumptions rather than facts?',
    'Would you change your opinion if key history were inaccurate?',
  ],
};

export function generateCrossExamination(
  medicalQuestion: string,
  diagnosis?: string,
): CrossExamCategory[] {
  const context = `${medicalQuestion} ${diagnosis ?? ''}`;
  return Object.entries(CROSS_EXAM_TEMPLATES).map(([name, templates]) => ({
    name,
    questions: templates.map((template) => ({
      question: personalizeQuestion(template, context),
      purpose: `Challenge ${name.toLowerCase()} assumptions and test expert reliability.`,
    })),
  }));
}

function personalizeQuestion(template: string, context: string): string {
  if (/stroke|tbi|brain/i.test(context)) {
    return template.replace(
      'this condition',
      'the reported stroke or brain injury',
    );
  }
  if (/cervical|neck/i.test(context)) {
    return template.replace('this condition', 'the cervical spine injury');
  }
  if (/lumbar|disc/i.test(context)) {
    return template.replace('this condition', 'the lumbar disc pathology');
  }
  return template;
}
